### ISSUE TITLE
re-connect MQTT when detect disconnection

### ISSUE THREAD

**Issue by taro-m** [KiiPlatform/gateway-agent#42]
When gateway detected disconnection of KiiCloud MQTT, It should try to re-connect automatically.

**Comment by yongpingchen** [comment]
@koron @satoshikumano 
Current implementation is storing mqtt client info to DB after connect to MQTT broker successfully. If connected fail, it will be not stored. 

When implementation of restore gateway it cause problem.  The steps of restoring:
1. clear DB relative to onboarding information 
2. onboard gateway. 
...

If the gateway is connecting to MQTT broker before restoring, then when restoring gateway, it requires onboard so that need connect to MQTT broker again. If the endpoint is not changed, then it is reconnect.

**Comment by taro-m** [comment]
implemented.
